# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('stock_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
