# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20170612_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='item',
            new_name='sale_item',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='free',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Sr'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Sr'),
        ),
    ]
