# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20170614_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Sr'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Sr'),
        ),
    ]
