# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20170614_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='item_total',
        ),
        migrations.AlterField(
            model_name='customer',
            name='sr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Sr'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Sr'),
        ),
    ]
