# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20170618_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Sr'),
        ),
        migrations.AlterField(
            model_name='purchasememo',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Sr'),
        ),
    ]
